VendornetVariableDB/Controllers/VariableMappingController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using VendornetVariableDB.Models;
using VendornetVariableDB.ViewModels;

namespace VendornetVariableDB.Controllers
{
    [Authorize]
    public class VariableMappingController : Controller
    {
        private ExtVariablesEntities db = new ExtVariablesEntities();

        // GET: ProgramVariableMaps
        public ActionResult Index()
        {
            // get all variables to choose from to add also
            var model = new ProgramVariableMapIndexViewModel()
            {
                Programs = db.Programs.Select(x => new SelectListItem { Text = x.ProgramName, Value = x.ProgramId.ToString() })
            };          
            return View(model);
        }

        public ActionResult GetMappingsForProgramOrItemsForDdlProcesses(int id)
        {
            var test = db.Processes.Count(x => x.ProgramId == id);

            if (db.Processes.Count(x=>x.ProgramId == id) == 0)
            {
                // it has ZERO processes, so return partial view for its variables at teh program level
                ProgramVariableMixedResultViewModel model = new ProgramVariableMixedResultViewModel
                {
                    IsSuccess = true,
                    ReturnType = 1,
                    ReturnHtml = RenderPartialView("_ProgramVariableMappingList", GetProgramVariableMappingsModelByProgramId(id))
                };
                return Json(model);
            }
            else
            {
                // it doesnt have processes, return selectlistitems for second ddl (processes)
                var availableVariables = db.Processes.Where(x => x.ProgramId == id)
                                                     .Select(x => new SelectListItem { Text = x.ProcessName.Trim(), Value = x.ProcessId.ToString() })
                                                     .ToList();
                ProgramVariableMixedResultViewModel model = new ProgramVariableMixedResultViewModel
                {
                    IsSuccess = true,
                    ReturnType = 2,
                    ReturnDDLOptions = availableVariables
                };
                return Json(model);
            }
            //return View();
        }
        
        public ProgramVariableMapsToReturnViewModel GetProgramVariableMappingsModelByProgramId(int id)
        {
            // conditional where clause in case they didn't select both ddls
            var existingProgramVariableMaps = db.ProgramVariableMaps.Where(x => x.ProgramId == id);

            // get available variables for this combination (none that are already chosen)
            var availableVariables = db.Variables.Where(x => !existingProgramVariableMaps.Any(x2 => x2.VariableId == x.VariableId))
                                                    .Select(x => new SelectListItem { Text = x.VariableName.Trim(), Value = x.VariableId.ToString() });        
            // build return model
            var returnModel = new ProgramVariableMapsToReturnViewModel
            {
                AvailableVariables = availableVariables,
                ExistingProgramVariableMaps = existingProgramVariableMaps
            };

            return returnModel;// PartialView("_ProgramVariableMappingList", returnModel);
        }

        public PartialViewResult GetProcessVariableMappings(VariableMapsToGetViewModel model)
        {          
            // conditional where clause in case they didn't select both ddls
            var existingProcessVariableMaps = (from pvm in db.ProcessVariableMaps
                                           where ((string.IsNullOrEmpty(model.ProcessId) ? false : pvm.ProcessId.ToString() == model.ProcessId))
                                           select pvm).AsEnumerable();

            // get available variables for this combination (none that are already chosen)
            var availableVariables = db.Variables.Where(x => !existingProcessVariableMaps.Any(x2 => x2.VariableId == x.VariableId))
                                                    .Select(x => new SelectListItem { Text = x.VariableName, Value = x.VariableId.ToString() });

            // build return model
            var returnModel = new ProcessVariableMapsToReturnViewModel
            {
                AvailableVariables = availableVariables,
                ExistingProcessVariableMaps = existingProcessVariableMaps
            };

            return PartialView("_ProcessVariableMappingList", returnModel);
        }
        
        [Authorize(Roles = "Admin")]
        public ActionResult AddProgramVariableMap(ProgramVariableMapToAddViewModel model)
        {
            // setup return model
            JsonResultViewModel returnModel = new JsonResultViewModel
            {
                IsSuccess = true
            };

            // remove all mappings first insead of checking which ones to remove and add and blah....
            db.ProgramVariableMaps.RemoveRange(db.ProgramVariableMaps.Where(x => x.ProgramId == model.ProgramId));
            db.SaveChanges();

            foreach (var item in model.AssignedVariables)
            {
                // setup model to create
                ProgramVariableMap pvm = new ProgramVariableMap
                {
                    ProgramId = model.ProgramId,
                    VariableId = Convert.ToInt32(item.VariableId),
                    Required = Convert.ToBoolean(item.IsRequired)
                };
                // give it a shot
                try
                {
                    db.ProgramVariableMaps.Add(pvm);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    returnModel.IsSuccess = false;
                    returnModel.Message = ex.Message;
                }
            }
            return Json(returnModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddProcessVariableMap(ProcessVariableMapToAddViewModel model)
        {
            // setup return model
            JsonResultViewModel returnModel = new JsonResultViewModel
            {
                IsSuccess = true
            };

            // remove all mappings first insead of checking which ones to remove and add and blah....
            db.ProcessVariableMaps.RemoveRange(db.ProcessVariableMaps.Where(x => x.ProcessId == model.ProcessId));
            db.SaveChanges();

            foreach (var item in model.AssignedVariables) {
                // setup model to create
                ProcessVariableMap pvm = new ProcessVariableMap
                {
                    ProcessId = model.ProcessId,
                    VariableId = Convert.ToInt32(item.VariableId),
                    Required = Convert.ToBoolean(item.IsRequired)
                };
                // give it a shot
                try
                {
                    db.ProcessVariableMaps.Add(pvm);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    returnModel.IsSuccess = false;
                    returnModel.Message = ex.Message;
                }
            }            
            return Json(returnModel);
        }

        // GET: ProgramVariableMaps/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProgramVariableMap programVariableMap = db.ProgramVariableMaps.Find(id);
            if (programVariableMap == null)
            {
                return HttpNotFound();
            }
            return View(programVariableMap);
        }

        // POST: ProgramVariableMaps/Delete/5
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken, Authorize(Roles = "Admin")]        
        public ActionResult DeleteConfirmed(int id)
        {
            ProgramVariableMap programVariableMap = db.ProgramVariableMaps.Find(id);
            db.ProgramVariableMaps.Remove(programVariableMap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        private string RenderPartialView(string viewName, object model)
        {
            ViewData.Model = model;
            using (System.IO.StringWriter writer = new System.IO.StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, writer);
                viewResult.View.Render(viewContext, writer);

                return writer.GetStringBuilder().ToString();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VendornetVariableDB/Views/VariableMapping/Create.cshtml
@model VendornetVariableDB.Models.ProgramVariableMap

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProgramVariableMap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProgramId, "ProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VariableId, "VariableId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VariableId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Required, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Required)
                    @Html.ValidationMessageFor(model => model.Required, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VendornetVariableDB/Views/VariableMapping/Delete.cshtml
@model VendornetVariableDB.Models.ProgramVariableMap

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProgramVariableMap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Required)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Required)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Program.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Program.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Variable.VariableName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Variable.VariableName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VendornetVariableDB/Views/VariableMapping/Details.cshtml
@model VendornetVariableDB.Models.ProgramVariableMap

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProgramVariableMap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Required)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Required)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Program.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Program.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Variable.VariableName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Variable.VariableName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VendornetVariableDB/Views/VariableMapping/Edit.cshtml
@model VendornetVariableDB.Models.ProgramVariableMap

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProgramVariableMap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProgramId)

        @Html.HiddenFor(model => model.VariableId)

        <div class="form-group">
            @Html.LabelFor(model => model.Required, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Required)
                    @Html.ValidationMessageFor(model => model.Required, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VendornetVariableDB/Views/VariableMapping/Index.cshtml
@model VendornetVariableDB.ViewModels.ProgramVariableMapIndexViewModel

@{
    ViewBag.Title = "Program Variable Mapping";
}

<h2>Variable Mapping</h2>

<div>
    <button id="btnBackNoUpdate" class="btn btn-sm">Back/No Update</button>
</div>
<br />

<div class="form-group">
    @Html.Label("Programs", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
    <div class="col-md-10">
        @Html.DropDownList("ddlPrograms", Model.Programs, "Choose...", new { @id = "ddlPrograms", @class = "form-control", @style = "max-width:350px;" })
    </div>
</div>

<div class="form-group" id="divProcessesDdl">
    @Html.Label("Processes", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
    <div class="col-md-10">
        <select id="ddlProcesses" class="form-control" style="max-width:350px;display:none;"></select>
    </div>
</div>

<br />
<br />
<div class="form-group" >
    <div id="divUserFeedback" class="text-center col-md-8">Please wait...<img src="@Url.Content("~/Content/Images/Loading.gif")"></div>
    <div class="col-md-4">&nbsp;</div>
</div>
<br />
<br />
<div id="divUserFeedbackMessage" class="text-center"></div>
<div id="divResults"></div>

<script>

    function ddlProcessesChanged() {
        // back button
        $('#btnBackNoUpdate').click(function () {
            parent.history.back();
            return false;
        });
        // blank results area
        $('#divResults').html('');
        // if they chose the 'choose...'
        if ($("#ddlProcesses").find("option:selected").val() == '') {
            // just return, nothing selected
            return;
        }
        // user feedback
        $('#divUserFeedback').show();
        // create data model
        var model = {
            ProgramId: $("#ddlPrograms").find("option:selected").val(),
            ProcessId: $("#ddlProcesses").find("option:selected").val()
        };
        // create model to pass
        var ajaxData = {
            //__RequestVerificationToken: token,
            model: model // FYI: must match name of param name of controller method
        };
        // get the mappings via ajax and return results to resultsDiv
        $.ajax({
            url: "@(Url.Action("GetProcessVariableMappings", "VariableMapping"))",
            type: "POST",
            data: ajaxData,
            success: function (response) { // ajax succeeded
                // hide userfeedback
                $('#divUserFeedback').hide();
                // load results into div
                $('#divResults').html(response);
            },
            error: function (response) { // ajax failure
                alert(response.responseText);
            }
        });
    }

    function ddlProgramsChanged() {
        // blank results area
        $('#divResults').html('');
        // blank sercond ddl
        $('#ddlProcesses').html('').hide();
        // show second ddl area
        $('#divProcessesDdl').hide();
        // if they chose the 'choose...'
        if ($("#ddlPrograms").find("option:selected").val() == '') {
            // just return, nothing selected
            return;
        }
        // user feedback
        $('#divUserFeedback').show();
        // create model to pass
        var ajaxData = {
            id: $("#ddlPrograms").find("option:selected").val()
        };
        // get the mappings via ajax and return results to resultsDiv
        $.ajax({
            url: "@(Url.Action("GetMappingsForProgramOrItemsForDdlProcesses", "VariableMapping"))",
            type: "POST",
            data: ajaxData,
            success: function (response) { // ajax succeeded
                if (response.IsSuccess) {
                    // hide userfeedback
                    $('#divUserFeedback').hide();
                    // switch on type of return, json for second ddl or partialview html
                    switch (response.ReturnType) {
                        case 1:
                            // load results into div
                            $('#divResults').html(response.ReturnHtml);
                            break;
                        case 2:
                            // load results into second ddl (processes)
                            var markup = '';
                            markup += '<option value="">Choose...</option>'; // initial blank
                            for (var x = 0; x < response.ReturnDDLOptions.length; x++) {
                                markup += '<option value="' + response.ReturnDDLOptions[x].Value + '">' + response.ReturnDDLOptions[x].Text + '</option>';
                            }
                            // show second ddl area
                            $('#divProcessesDdl').show();
                            // show second ddl
                            $('#ddlProcesses').html(markup).show();
                            break;
                    }
                } else {
                    alert("FAILED\n" + response.ReturnHtml);
                    // hide userfeedback
                    $('#divUserFeedback').hide();
                }
            },
            error: function (response) { // ajax failure
                alert(response.responseText);
            }
        });
    }

    $(document).ready(function () {

        // hide feedback initially onload
        $('#divUserFeedback').hide();

        // hide second ddl area
        $('#divProcessesDdl').hide();

        /* on change of first DDL, load second(processes) ddl options
           or get existing var maps and available vars for that program*/
        $('#ddlPrograms').change(function () {
            ddlProgramsChanged();
        });

        // on change of either ddl, refresh mapping list
        $("#ddlProcesses").change(function () {
            ddlProcessesChanged();
        });

    });

</script>