VendornetVariableDB/Controllers/ClientAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using VendornetVariableDB.Models;
using System.Web.Script.Serialization;
using VendornetVariableDB.ViewModels;
using VendornetVariableDB.Classes;

namespace VendornetVariableDB.Controllers
{
    [Authorize]
    public class ClientAccountController : Controller
    {
        private ExtVariablesEntities _varDB = new ExtVariablesEntities();

        public ActionResult Index(int serverId)
        {
            // get account info
            List<GetAccountsAvailability_Result> cilentAccounts = (from gaa in _varDB.GetAccountsAvailability(serverId) select gaa).ToList();
            List<GetAccountsAvailability_Result> serverAccounts = new List<GetAccountsAvailability_Result>();
            List<GetAccountsAvailability_Result> availableAccounts = new List<GetAccountsAvailability_Result>();
            // sort accounts
            foreach (GetAccountsAvailability_Result clientAccount in cilentAccounts)
            {
                if (clientAccount.ServerAccountId == null)
                {
                    availableAccounts.Add(clientAccount);
                }
                else
                {
                    serverAccounts.Add(clientAccount);
                }
            }

            // fill returnModel
            var returnModel = new ClientAccountIndexViewModel()
            {
                // tierinfo
                TierInfo = new TierInfo()
                {
                    ServerId = serverId,
                    ServerName = (from s in _varDB.Servers where s.ServerId == serverId select s.ServerName).First().ToString(),
                },
                // accounts
                AvailableAccounts = availableAccounts,
                ServerAccounts = serverAccounts
            };           

            return View(returnModel);
        }

        public ActionResult Modify(int serverAccountId)
        {
            List<GetAccountVariables_Result> clientAccountVariables = (from apv in _varDB.GetAccountVariables(serverAccountId) select apv).ToList();

            var replacements = (from r in _varDB.FindReplaces
                                where r.Find.Contains("Server") || r.Find.Contains("Account")
                                select new { r.Find, r.ReplaceWith }).ToList();

            List<GetAccountVariables_Result> currentVars = new List<GetAccountVariables_Result>();
            List<GetAccountVariables_Result> addRecommendedVars = new List<GetAccountVariables_Result>();
            List<GetAccountVariables_Result> addNonRecommendedVars = new List<GetAccountVariables_Result>();

            foreach (GetAccountVariables_Result clientAccountVariable in clientAccountVariables)
            {
                if (clientAccountVariable.AccountVariableId != null)
                {
                    // AccountAccountVariables.AccountAccountVariableId is the primary key and it has a value; this value is already set and can be modified
                    currentVars.Add(clientAccountVariable);
                }
                else
                {
                    // AccountAccountVariables.AccountAccountVariableId is the primary key and it is null;
                    //    this variable does not exist at this level for this server/account/Account/Account
                    if (clientAccountVariable.DefaultLevel == (byte)Enums.VariableLevelEnum.Account)
                    {
                        // DefaultLevel 2 means this variable is recommended to be set at the Account level
                        addRecommendedVars.Add(clientAccountVariable);
                    }
                    else
                    {
                        // It is not recommended that this variable be set at the Account level; however, it is allowed to be set at that level
                        addNonRecommendedVars.Add(clientAccountVariable);
                    }
                }
            }

            List<FindReplaceModel> findReplacements = new List<FindReplaceModel>();

            foreach (var replacement in replacements)
            {
                findReplacements.Add(new FindReplaceModel(replacement.Find, replacement.ReplaceWith));
            }

            // does not work, even when using public class AvailableVariables : IEquatable<GetAccountVariables_Result>
            //availableVariables = availableVariables.RemoveAll(item => accountProgramVariables.Contains(item));

            // possible to do these below in 1 command? same record in table (ServerAccounts)
            int serverId = (from sa in _varDB.ServerAccounts where sa.ServerAccountId == serverAccountId select sa.ServerId).First();
            int accountId = (from sa in _varDB.ServerAccounts where sa.ServerAccountId == serverAccountId select sa.AccountId).First();


            TierInfo tierInfo = new TierInfo
            {
                ServerAccountId = serverAccountId,
                ServerId = serverId,
                ServerName = clientAccountVariables.First().ServerName,
                AccountId = accountId,
                AccountName = clientAccountVariables.First().AccountName,
            };

            AccountModifyViewModel model = new AccountModifyViewModel()
            {
                TierInfo = tierInfo,
                CurrentVariables = currentVars,
                AddRecommendedVars = addRecommendedVars,
                AddNonRecommendedVars = addNonRecommendedVars,
                Replacements = findReplacements
            };
            
            return View(model);
        }

        [Authorize(Roles = "Admin,User")]
        public ActionResult AddAccount(string values)
        {
            UpdateSetupObj updates = new JavaScriptSerializer().Deserialize<UpdateSetupObj>(values);

            try
            {
                ServerAccount dataToAdd = new ServerAccount()
                {
                    ServerId = updates.ServerId,
                    AccountId = updates.AccountId
                };

                _varDB.ServerAccounts.Add(dataToAdd);
                _varDB.SaveChanges();

                var redirectUrl = new UrlHelper(Request.RequestContext).Action("Server", "Controller");

                // "Successfully added " + updates.Name + ": " + updates.Data + " to AccountProgramVariables."
                return Json(redirectUrl, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json("Change Failed : " + e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, Authorize(Roles = "Admin,User")]
        public ActionResult RemoveAccount(string values)
        {
            UpdateSetupObj updates = new JavaScriptSerializer().Deserialize<UpdateSetupObj>(values);

            ServerAccount delThis = _varDB.ServerAccounts.Find(updates.PKeyId);

            try
            {
                _varDB.ServerAccounts.Remove(delThis);
                _varDB.SaveChanges();
                return Json("Successfully deleted ServerAccount " + updates.PKeyId.ToString(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json("Change Failed : " + e.Message, JsonRequestBehavior.AllowGet);
            }
        }
       
        [HttpPost, Authorize(Roles = "Admin,User")]
        public ActionResult AddAccountVariable(string values)
        {
            UpdateVariableObj updates = new JavaScriptSerializer().Deserialize<UpdateVariableObj>(values);

            try
            {
                AccountVariable dataToAdd = new AccountVariable()
                {
                    ServerAccountId = updates.ServerAccountId,
                    VariableId = updates.VariableId,
                    VariableData = updates.Data,
                    User = User.Identity.Name
                };

                _varDB.AccountVariables.Add(dataToAdd);
                _varDB.SaveChanges();

                var redirectUrl = new UrlHelper(Request.RequestContext).Action("Account", "Controller");

                // "Successfully added " + updates.Name + ": " + updates.Data + " to AccountProgramVariables."
                return Json(redirectUrl, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json("Change Failed : " + e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, Authorize(Roles = "Admin,User")]
        public ActionResult DeleteAccountVariable(string values)
        {
            UpdateVariableObj updates = new JavaScriptSerializer().Deserialize<UpdateVariableObj>(values);
            AccountVariable delThis = _varDB.AccountVariables.Find(updates.PKeyId);

            try
            {
                _varDB.AccountVariables.Remove(delThis);
                _varDB.SaveChanges();
                return Json("Successfully deleted " + updates.Name, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json("Change Failed : " + e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, Authorize(Roles = "Admin,User")]
        public ActionResult UpdateAccountVariable(string values)
        {
            UpdateVariableObj updates = new JavaScriptSerializer().Deserialize<UpdateVariableObj>(values);

            AccountVariable variableToChange = _varDB.AccountVariables.Find(updates.PKeyId);

            variableToChange.VariableData = updates.Data;
            variableToChange.User = User.Identity.Name;

            try
            {
                _varDB.SaveChanges();

VendornetVariableDB/Views/ClientAccount/Index.cshtml
@model VendornetVariableDB.ViewModels.ClientAccountIndexViewModel
@{
    ViewBag.Title = "Accounts Page";
}

<div class="jumbotron">
    @Html.Action("TierLocation", "Partials", Model.TierInfo)
    <p class="lead">Please select the <b>ACCOUNT</b> whose variables you would like to modify.</p>
    <br />
    <select id="serverAccountSelect" onchange="removeButton()">
        @foreach (var serverAccount in Model.ServerAccounts)
        {
            <option value="@serverAccount.ServerAccountId,@serverAccount.HasProgram">@serverAccount.AccountName</option>
        }
    </select>
    <span>
        <button onclick="getAccountVariables()" class="btn btn-primary btn-lg">Modify Account Variables</button>
        <button onclick="getAccountPrograms()" class="btn btn-primary btn-lg">View Programs &raquo;</button>
        <button id="deleteClientAccount" onclick="removeAccount();" class="btn btn-primary btn-lg" style="display:none">Remove Account from Server</button>
    </span>
    <br /><br />
    <div id="divAddAccount">
        <select id="accountAdd">
            @foreach (var availableAccount in Model.AvailableAccounts)
            {
                <option value="@availableAccount.AccountId">@availableAccount.AccountName</option>
            }
        </select>
        <button onclick="addAccount()" class="btn btn-primary btn-success">Add Account</button>
    </div>
    <div>
        <button id="btnBackNoUpdate" class="btn btn-sm">Back/No Update</button>
    </div>
</div>

<script>
      // back button
    $('#btnBackNoUpdate').click(function(){
        parent.history.back();
        return false;
    });
    var testMode = false;

    var serverAccountSelect = document.getElementById("serverAccountSelect");
    var selectedAccount;
    var hasPrograms;

    function getServerAccountId() {
        var sel = serverAccountSelect.options[serverAccountSelect.selectedIndex].value;
        var arr = sel.split(",");

        return parseInt(arr[0]);
    }

    function getAccountPrograms() {
        selectedServerAccountId = getServerAccountId();
        location.href = '@Url.Action("Index", "Program")?serverAccountId=' + selectedServerAccountId;
    }

    function getAccountVariables() {
        selectedServerAccountId = getServerAccountId();
        location.href = '@Url.Action("Modify", "ClientAccount")?serverAccountId=' + selectedServerAccountId;
    }

    function removeButton() {
        selectedServerAccountId = getServerAccountId();
        var sel = serverAccountSelect.options[serverAccountSelect.selectedIndex].value;
        var arr = sel.split(",");

        hasPrograms = Boolean(parseInt(arr[1]));

        if (!hasPrograms) {
            // cannot delete from ServerAccounts if the account ever had a variable set due to foreign key constraint on AccountProgramVariables_Hist
            // TBD if the constraint is needed

            //document.getElementById("deleteClientAccount").style.display = 'inline-block';
            document.getElementById("deleteClientAccount").style.display = 'none';
        } else {
            document.getElementById("deleteClientAccount").style.display = 'none';
        }

        // if this selected value (!HasPrograms) then display a delete button
    }

    function addAccount() {
        var accountId = $("#accountAdd").find("option:selected").val(); //document.getElementById("accountAdd").val();
        var dataStr = ({
            ServerId: @Model.TierInfo.ServerId,
            AccountId: accountId
        });

        dataStr = JSON.stringify(dataStr);
        
        if (testMode) {
            window.alert(dataStr);
            return;
        }

        $.ajax({
            dataType: 'json',
            url: "@Url.Action("AddAccount", "ClientAccount")",
            type: 'POST',
            data: { values: dataStr },
            success: function (result) {
                // recommended standard appears to be having json respond with the url; if so then update this to reload (with view arguments: ?serverId=...)
                location.reload();
                //alert("Server responded with message: " + result);
            },
            failure: function (response) {
                alert("Server responded with message: " + response);
            }
        });
    }

    function removeAccount() {
        selectedServerAccountId = getServerAccountId();

        var dataStr = ({
            PKeyId: selectedServerAccountId
        });

        dataStr = JSON.stringify(dataStr);

        if (testMode) {
            window.alert(dataStr);
            return;
        }

        $.ajax({
            dataType: 'json',
            url: "@Url.Action("RemoveAccount", "ClientAccount")",
            type: 'POST',
            data: { values: dataStr },
            success: function (result) {
                // recommended standard appears to be having json respond with the url; if so then update this to reload (with view arguments: ?serverId=...)
                location.reload();
                //alert("Server responded with message: " + result);
            },
            failure: function (response) {
                alert("Server responded with message: " + response);
            }
        });
    }

    $(document).ready(function () {

        // if not available account, blank out the add account section (div)
        @{
            if (Model.AvailableAccounts.Count == 0)
            {
            <text>
            $('#divAddAccount').hide();
            </text>
            }
        }

    });


</script>