VendornetVariableDB/Models/VariableDefault.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendornetVariableDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableDefault
    {
        public int DefaultId { get; set; }
        public int VariableId { get; set; }
        public Nullable<byte> AccountType { get; set; }
        public bool Server { get; set; }
        public bool Account { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual AccountType AccountType1 { get; set; }
    }
}

VendornetVariableDB/Controllers/VariableDefaultsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using VendornetVariableDB.Models;
using VendornetVariableDB.ViewModels;

namespace VendornetVariableDB.Controllers
{
    [Authorize]
    public class VariableDefaultsController : Controller
    {
        private ExtVariablesEntities db = new ExtVariablesEntities();

        // GET: Variables
        public ActionResult Index()
        {
            VariableIndexViewModel model = new VariableIndexViewModel()
            {
                AvailableVariables =
                    db.v_Defaults
                        .OrderBy(z => z.VariableName)
                        .Select(x => new DDLWithDescriptionViewModel { Id = x.VariableId.ToString(),
                                                                       Name = x.VariableName,
                                                                       Description = x.VariableDescription })
                        .Distinct(),
                    //db.v_Defaults
                    //    //.Where(z=>//z.VariableId == 40 
                    //    //   //&& (z.ThisLevel == z.DefaultLevel || z.ProgramId == 3) // this is at account level
                    //    //   //&& 
                    //    //   //z.AccountType == 1
                    //    //   )
                    //    .OrderBy(y=>y.VariableName)
                    //    .Select(x => new SelectListItem {Text = x.VariableName, Value = x.VariableId.ToString()})
                    //    .Distinct(),

                 AccountTypes =
                    db.AccountTypes
                        //.Where(z => z.VariableId == 40
                        //   //&& (z.ThisLevel == z.DefaultLevel || z.ProgramId == 3) // this is at account level
                        //   && z.AccountType == 1)
                        .OrderBy(y => y.AccountTypeDesc)
                        .Select(x => new SelectListItem { Text = x.AccountTypeDesc, Value = x.AccountType1.ToString() })
                        .Distinct()                        
            }; 
            return View(model);
        }        

        public PartialViewResult GetVariablesToEdit(VariableGetVariablesToEditViewModel modelIn)
        {
            var testObj = db.v_Defaults
                        .Where(z => z.VariableId == modelIn.VariableTypeId
                           && z.AccountType == modelIn.AccountTypeId);

            VariableGetVariablesToEditViewModel model = new VariableGetVariablesToEditViewModel()
            {
                VariablesToEdit = testObj
                    .Select(x => new VariableToEditViewModel
                    {
                        VariableId = x.VariableId ?? 0,
                        VariableName = x.VariableName,
                        VariableDescription = x.VariableDescription,
                        Account = x.Account,
                        DefaultLevel = x.DefaultLevel,
                        DefaultValue = x.DefaultValue,
                        LevelId = x.ThisLevel,
                        ProgramId = x.ProgramId.Value.ToString() ?? string.Empty,
                        ProgramName = x.ProgramName,
                        ProcessId = x.ProcessId.Value.ToString() ?? string.Empty,
                        ProcessName = x.ProcessName,
                        Server = x.Server,
                        ThisLevel = x.ThisLevel
                    })
                    .ToList(),
                VariableTypeId = modelIn.VariableTypeId,
                AccountTypeId = modelIn.AccountTypeId
            };

            return PartialView("_VariableGetVariablesToEdit", model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UpdateVariable(VariableUpdateViewModel model)
        {
            // setup json return model
            JsonResultViewModel returnModel = new JsonResultViewModel();
                
            try
            {
                // variableDefault to update
                var variableDefaultToEdit = db.VariableDefaults
                                         .FirstOrDefault(
                                                x => x.VariableId == model.VariableId
                                                      && x.Server == model.Server
                                                      && x.Account == model.Account
                                                      && x.AccountType == model.AccountType
                                                      && x.ProcessId == model.ProcessId
                                                      && x.ProgramId == model.ProgramId
                                                      );
                // if exists, update
                if (variableDefaultToEdit != null)
                {
                    variableDefaultToEdit.DefaultValue = model.DefaultValue;
                    // tell repo
                    db.Entry(variableDefaultToEdit).State = EntityState.Modified;
                }
                else
                {
                    // create new
                    var varDefaultNew = new VariableDefault()
                    {
                        Account = model.Account,
                        AccountType = byte.Parse(model.AccountType.ToString()),
                        DefaultValue = model.DefaultValue,
                        ProcessId = model.ProcessId,
                        ProgramId = model.ProgramId,
                        Server = model.Server,
                        VariableId = model.VariableId
                    };
                    db.VariableDefaults.Add(varDefaultNew);
                }
                // save changes
                db.SaveChanges();

                // return model
                returnModel = new JsonResultViewModel()
                {
                    IsSuccess = true,
                    Message = string.Empty
                };
            }
            catch(Exception ex)
            {
                returnModel.IsSuccess = false;
                returnModel.Message = ex.Message;
                return Json(returnModel, JsonRequestBehavior.AllowGet);
                //throw ex;
            }
            // return for ajax
            return Json(returnModel, JsonRequestBehavior.AllowGet);
        }

        // GET: Variables/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            v_Defaults v_Defaults = db.v_Defaults.Find(id);
            if (v_Defaults == null)
            {
                return HttpNotFound();
            }
            return View(v_Defaults);
        }

        // GET: Variables/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Variables/Create
        [HttpPost, Authorize(Roles = "Admin"), ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DefaultId,VariableId,Server,Account,ProgramId,ProcessId,AccountType,AccountTypeDesc,VariableName,ProgramName,ProcessName,DefaultValue,ThisLevel,DefaultLevel")] v_Defaults v_Defaults)
        {
            if (ModelState.IsValid)
            {
                db.v_Defaults.Add(v_Defaults);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(v_Defaults);
        }

        // GET: Variables/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            v_Defaults v_Defaults = db.v_Defaults.Find(id);
            if (v_Defaults == null)
            {
                return HttpNotFound();
            }
            return View(v_Defaults);
        }

        // POST: Variables/Edit/5
        [HttpPost, Authorize(Roles = "Admin"), ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DefaultId,VariableId,Server,Account,ProgramId,ProcessId,AccountType,AccountTypeDesc,VariableName,ProgramName,ProcessName,DefaultValue,ThisLevel,DefaultLevel")] v_Defaults v_Defaults)
        {
            if (ModelState.IsValid)
            {
                db.Entry(v_Defaults).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(v_Defaults);
        }

        // GET: Variables/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            v_Defaults v_Defaults = db.v_Defaults.Find(id);
            if (v_Defaults == null)
            {
                return HttpNotFound();
            }
            return View(v_Defaults);
        }

        // POST: Variables/Delete/5
        [HttpPost, ActionName("Delete"), Authorize(Roles = "Admin"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            v_Defaults v_Defaults = db.v_Defaults.Find(id);
            db.v_Defaults.Remove(v_Defaults);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VendornetVariableDB/Views/VariableDefaults/Create.cshtml
@model VendornetVariableDB.Models.v_Defaults

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>v_Defaults</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DefaultId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VariableId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VariableId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VariableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Server, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Server, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Server, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProcessId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProcessId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProcessId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountTypeDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountTypeDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountTypeDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VariableName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VariableName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VariableName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProcessName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProcessName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProcessName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThisLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThisLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThisLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VendornetVariableDB/Views/VariableDefaults/Delete.cshtml
@model VendornetVariableDB.Models.v_Defaults

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>v_Defaults</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DefaultId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VariableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VariableId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Server)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Server)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountTypeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountTypeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DefaultValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultValue)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VendornetVariableDB/Views/VariableDefaults/Details.cshtml
@model VendornetVariableDB.Models.v_Defaults

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>v_Defaults</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DefaultId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VariableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VariableId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Server)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Server)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountTypeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountTypeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DefaultValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultValue)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VendornetVariableDB/Views/VariableDefaults/Index.cshtml
@model VendornetVariableDB.ViewModels.VariableIndexViewModel

@{
    ViewBag.Title = "Variable Defaults";

    // make new SelectList from model.AvailableVariables
    var DdlVariableNames = new SelectList(Model.AvailableVariables, "Id", "Name");

    // made a dictionary of varId and description
    //var dictVariableIdDescription = new Dictionary<string, string> {"jj", "jj" };

}
@Html.Partial("_LegendVariableCodeTranslation")

<script>   
    // JSON the available variables so we can match up the selected DDL value with the var description
    var JSONAvailableVariables = @Html.Raw(Json.Encode(Model.AvailableVariables));
</script>

<h2>Variable Defaults</h2>

<div>
    <button id="btnBackNoUpdate" class="btn btn-sm">Back/No Update</button>
</div>
<br />

<div class="form-group col-md-5" style="float:right; clear:left;">
    <div id="divDisplayCurrentChoices"></div>
    Description:<div id="divDisplayCurrentChoiceDescription" class="alert alert-warning divDisplayCurrentChoiceDescription"></div>
</div>

<div class="form-group">
    @Html.Label("Available Variables", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.DropDownList("VariableNames", DdlVariableNames, "Choose...", new { @id = "VariableNames", @class = "form-control", @style = "max-width:350px;" })
    </div>
</div>
<br />

<div class="form-group">
    @Html.Label("Account Types", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.DropDownList("AccountTypes", Model.AccountTypes, "Choose...", new { @id = "AccountTypes", @class = "form-control", @style = "max-width:350px;" })
    </div>
</div>
<br />

<div class="form-group">
    @Html.Label(" ", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        <button id="btnGetVariablesFromDDLs" class="form-control" style="max-width:250px;">Get Variables To Edit</button>
    </div>
</div>
<br />
<br />

<div id="" class="form-group col-md-12" style="color:white;background-color:green;height:20px;width:100%;text-align:center;vertical-align:middle;clear:both;">
    <p>*** Recommended variables are displayed in green ***</p>
</div>

<div id="divVariablesToEdit" class="form-group col-md-12"></div>
<br />
<div id="divUserFeedback" class="text-center">Please wait...<img src="@Url.Content("~/Content/Images/Loading.gif")"></div>



<script>
    $(document).ready(function () {
        // on change of DDLAccountVariables, load/switch variable description in label
        $('#VariableNames').change(function () {
            var selectedId = $("#VariableNames").find("option:selected").val();
            // iterate over each element in the array
            for (var i = 0; i < JSONAvailableVariables.length; i++) {
                // look for the entry with a matching `code` value
                if (JSONAvailableVariables[i].Id == selectedId) {
                    // we found it
                    $('#divDisplayCurrentChoiceDescription').html(JSONAvailableVariables[i].Description);
                    //console.log(JSONAvailableVariables[i].Description);
                    break;
                }
            }
        });
        // instructions modal
        var cookieInstructionsOnce = $.cookie("cookieInstructionsOnce");
        if (!cookieInstructionsOnce) {
            $('#modalInstructions').modal('show'); // show modal
            $.cookie("cookieInstructionsOnce", 1, {
                expires: 30,           //expires in 10 days
                //path: '/',          //The value of the path attribute of the cookie 
                //(default: path of page that created the cookie).
                //domain: 'gsiccorp.net',  //The value of the domain attribute of the cookie
                //(default: domain of page that created the cookie).
                secure: true          //If set to true the secure attribute of the cookie
                //will be set and the cookie transmission will
                //require a secure protocol (defaults to false).
            });// set cookie
        }
        // show instructions button
        $('#btnShowInstructionModal').click(function () {
            $('#modalInstructions').modal('show');
        });
        // back button
        $('#btnBackNoUpdate').click(function () {
            parent.history.back();
            return false;
        });
        // hide spinner initially
        $('#divUserFeedback').hide();

        // ddl onChange: blank the results and feedback divs
        $('#VariableNames, #AccountTypes').on('change', function () {
            $('#divVariablesToEdit').html('');
            $('#divDisplayCurrentChoices').html('');
        });

        // onClick 
        $("#btnGetVariablesFromDDLs").click(function () {

            // get selected value from DDLs
            var variableTypeId = $("#VariableNames").find("option:selected").val();
            var accountTypeId = $("#AccountTypes").find("option:selected").val();

            if (!variableTypeId || !accountTypeId) {
                alert('Please select from both drop-downs.');
                return;
            }
                       
            // get token from form
            var token = $('input[name="__RequestVerificationToken"]').val();

            // create model to pass
            var ajaxData = {
                __RequestVerificationToken: token,
                VariableTypeId: variableTypeId,
                AccountTypeId: accountTypeId,
                VariablesToEdit: null
            }

            // show spinner
            $('#divUserFeedback').show();

            // blank result area
            $('#divVariablesToEdit').html('');

            // ajax load to controller
            $.ajax({
                type: "post",
                url: '@Url.Action("GetVariablesToEdit", "VariableDefaults")',
                data: ajaxData,
                //datatype: "json",
                success: function (data) {
                    // hide spinner
                    $('#divUserFeedback').hide();
                    // load returned values into element
                    $('#divVariablesToEdit').html(data);
                    // user feedback: show which variables are being shown in divDisplayCurrentChoices
                    var someHTML = '<div class="alert-info">Defaults currently displayed for:<ul>' +
                                       '<li>Variable: <b>' + $("#VariableNames").find("option:selected").text() + '</b></li>' +
                                       '<li>Account Type: <b>' + $("#AccountTypes").find("option:selected").text() + '</b></li>' +
                                   '</ul></div>';
                    $('#divDisplayCurrentChoices').html(someHTML);
                },
                fail: function (data) {
                    // inform of error
                    alert("FAILED\nError: " + data.error);
                    // hide spinner
                    $('#divUserFeedback').hide();
                }
            });
          
        });

    });
</script>