VendornetVariableDB/Controllers/RolesController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using VendornetVariableDB.Models;
using System.Collections.Generic;

namespace VendornetVariableDB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        //private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }
        public ApplicationDbContext context = ApplicationDbContext.Create();
        // GET: Roles
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            return View(roles);
        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>

            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();

            var nameList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>

            new SelectListItem { Value = uu.UserName, Text = uu.UserName }).ToList();
            ViewBag.Roles = list;
            ViewBag.Users = nameList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            UserManager.AddToRole(user.Id, RoleName);

            ViewBag.ResultMessage = "Role created successfully !";

            getRelatedRoles(user.Id);
            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                ViewBag.RolesForThisUser = UserManager.GetRoles(user.Id);

                getRelatedRoles(user.Id);
            }

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (UserManager.IsInRole(user.Id, RoleName))
            {
                UserManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            getRelatedRoles(user.Id);

            return View("ManageUserRoles");
        }

        private void getRelatedRoles(string userId)
        {
            var nameList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName, Text = uu.UserName }).ToList();
            ViewBag.Users = nameList;
            ViewBag.RolesForThisUser = UserManager.GetRoles(userId);
            List<string> fullRolesList = context.Roles.Select(r => r.Name).ToList();

            List<SelectListItem> ContainedRoles = new List<SelectListItem>();
            List<SelectListItem> NotContainedRoles = new List<SelectListItem>();
            IList<string> containedRolesList = UserManager.GetRoles(userId);

            foreach (var roleName in containedRolesList)
            {
                ContainedRoles.Add(new SelectListItem { Value = roleName, Text = roleName });
            }

            foreach (var roleName in fullRolesList)
            {
                if (!containedRolesList.Contains(roleName.Trim()))
                {
                    NotContainedRoles.Add(new SelectListItem { Value = roleName, Text = roleName });
                }
            }

            if (ContainedRoles.Count > 0)
            {
                ViewBag.ContainedRoles = ContainedRoles;
            }

            if (NotContainedRoles.Count > 0)
            {
                ViewBag.NotContainedRoles = NotContainedRoles;
            }
        }
    }
}

VendornetVariableDB/Views/Roles/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Role</h2>
@Html.ActionLink("List Roles", "Index") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        Role name
    </div>
    <p>
        @Html.TextBox("RoleName")
    </p>
    <input type="submit" value="Save" />
}

VendornetVariableDB/Views/Roles/Edit.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Role</h2>

@Html.ActionLink("List Roles", "Index") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    <div>
        Role name
    </div>
    <p>
        @Html.TextBoxFor(model => model.Name)
    </p>
    <input type="submit" value="Save" />
}

VendornetVariableDB/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Roles Listing </h2>

@Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
<div>
    @foreach (var role in Model)
    {
        <p>
            <strong>@role.Name | </strong>
            <span onclick="return confirm('Deleting a Role will break the code anywhere the Role was used to limit users.\nThis should be done by Software Engineers only.\nAre you sure to delete?')"><a href="@(Url.Action("Delete", "Roles", new { RoleName = role.Name }))" class="delLink" style="color:red;">Delete</a></span> |
            @Html.ActionLink("Edit", "Edit", new { roleName = @role.Name })
        </p>
    }
</div>

VendornetVariableDB/Views/Roles/ManageUserRoles.cshtml
@{
    ViewBag.Title = "ManageUserRoles";
}

<h2>Manage User Roles</h2>
@Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />

<h2>Select a User</h2>
@using (Html.BeginForm("GetRoles", "Roles"))
{
    @Html.AntiForgeryToken()
    <p>
        Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users, "Select ...", new {@class = "form-control", onload = "$('#UserName').prop('selectedIndex', -1);", onchange = "if (document.getElementById('UserName').options[document.getElementById('UserName').selectedIndex].value != '') {this.form.submit();} " })
    </p>
}

@if (ViewBag.RolesForThisUser != null)
{
    <div>
        <h2>Roles for this user </h2>
        <ol>
            @foreach (string s in ViewBag.RolesForThisUser)
            {
                <li>@s</li>
            }
        </ol>
    </div>
}

@if (ViewBag.NotContainedRoles != null)
{
    <h2>Add Role for User:</h2>
    using (Html.BeginForm("RoleAddToUser", "Roles"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>
            <span style="display:none;">Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users)</span>
            Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.NotContainedRoles, new { @class = "form-control" })

        </p>

        <input type="submit" value="Save" class="form-control" />
    }
}

@if (ViewBag.ContainedRoles != null)
{
    <h2>Delete User from Role:</h2>
    using (Html.BeginForm("DeleteRoleForUser", "Roles"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>
            <span style="display:none;">Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users)</span>
            Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.ContainedRoles, new { @class = "form-control" })

        </p>

        <input type="submit" value="Delete this user from Role" class="form-control" />
     }
}